import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "test1@test.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Elsa",
      email: "elsa1@test.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Addidas",
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Fit Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 170,
      brand: "Gucci",
      rating: 4.5,
      numReviews: 2,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 240,
      brand: "Gucci",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: " Popular pants",
    },
    {
      name: "Wide Leg Pants",
      slug: "wide-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 42,
      brand: "Zara",
      rating: 1.5,
      numReviews: 5,
      countInStock: 20,
      description: " Popular pants",
    },
    {
      name: "Casual Pants",
      slug: "casual-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 50,
      brand: "Puma",
      rating: 4.9,
      numReviews: 12,
      countInStock: 20,
      description: " Popular pants",
    },
  ],
};

export default data;
